package cpen221.mp3.client;

public enum RequestCommand {
    CONFIG_UPDATE_MAX_WAIT_TIME,
    CONTROL_SET_ACTUATOR_STATE,
    CONTROL_TOGGLE_ACTUATOR_STATE,
    CONTROL_NOTIFY_IF,
    ANALYSIS_GET_EVENTS_IN_WINDOW,
    ANALYSIS_GET_ALL_ENTITIES,
    ANALYSIS_GET_LATEST_EVENTS,
    ANALYSIS_GET_MOST_ACTIVE_ENTITY,
    PREDICT_NEXT_N_TIMESTAMPS,
    PREDICT_NEXT_N_VALUES
}